name: Plan Terraform Workflow

on:
  workflow_call:
    inputs:
      cloud_provider:
        required: true
        type: string

      environment:
        required: true
        type: string

      update_lock_file:
        required: false
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      cloud_provider:
        description: Cloud Provider
        required: true
        type: choice
        options:
        - azure
        - aws

      environment:
        description: Environment
        required: false
        type: choice
        default: dev
        options:
        - dev
        - prod

      update_lock_file:
        required: false
        type: boolean
        default: false

env:
  TF_VERSION: '1.9.8'

jobs:
  terraform_plan:
    runs-on: robot-shop-runner
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set AWS Credentials
      if: ${{ inputs.cloud_provider == 'aws' }}
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "Configured AWS creds"

    - name: Set Azure Credentials
      if: ${{ inputs.cloud_provider == 'azure' }}     
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID_TERRAFORM }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET_TERRAFORM }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "Configured Azure creds"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      if: ${{ inputs.update_lock_file }}
      run: |
        terraform init
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .terraform.lock.hcl
        git commit -m "Updated Terraform lock file"
        git push
      working-directory: ${{ inputs.cloud_provider }}

    - name: Terraform Init without lock file update
      if: ${{ !inputs.update_lock_file }}
      run: terraform init -backend=false
      working-directory: ${{ inputs.cloud_provider }}

    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{ inputs.cloud_provider }}

    - name: Terraform Plan
      run: |
        terraform plan -var-file=${{ inputs.environment }}.tfvars -out=tfplan
      working-directory: ${{ inputs.cloud_provider }}

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: ${{ inputs.cloud_provider }}/tfplan