name: Plan Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      cloud_provider:
        description: Cloud Provider
        required: true
        type: choice
        options:
        - azure
        - aws

      environment:
        description: Environment
        required: false
        type: choice
        default: dev
        options:
        - dev
        - prod

env:
    TF_VERSION: '1.9.8'

jobs:
  terraform:
    runs-on: robot-shop-runner
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set AWS Credentials
      if: ${{ inputs.cloud_provider == 'aws' }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: echo "Configured AWS creds"

    - name: Set Azure Credentials
      if: ${{ inputs.cloud_provider == 'azure' }}
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TERRAFORM }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET_TERRAFORM }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: echo "Configured Azure creds"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ inputs.cloud_provider }}

    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{ inputs.cloud_provider }}

    - name: Terraform Plan
      run: |
        terraform plan -var-file=${{ inputs.environment }}.tfvars
      working-directory: ${{ inputs.cloud_provider }}